# Generated by Django 4.2.16 on 2025-04-05 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Мактаб', 'verbose_name_plural': 'Мактабҳо'},
        ),
        migrations.AddField(
            model_name='school',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='schools', to='Menu.book', verbose_name='Китобҳои мактаб'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(verbose_name='Нақшаи мактаб'),
        ),
        migrations.AlterField(
            model_name='school',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Таърихи таъсисёбӣ'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Номи мактаб'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Рақами телефон'),
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Миқдори китоб')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Вақти гирифтани китоб')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.book', verbose_name='Китоб')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.school', verbose_name='Мактаб')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Донишҷӯ')),
            ],
            options={
                'verbose_name': 'Китоби донишҷӯ',
                'verbose_name_plural': 'Китобҳои донишҷӯён',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='students_book',
            field=models.ManyToManyField(blank=True, related_name='books', through='Menu.StudentBook', to=settings.AUTH_USER_MODEL, verbose_name='Китобҳое, ки аз ҷониби донишҷӯён гирифта шудаанд'),
        ),
    ]
