# Generated by Django 4.2.16 on 2025-04-06 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_school_options_school_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='books',
        ),
        migrations.RemoveField(
            model_name='school',
            name='students_book',
        ),
        migrations.AddField(
            model_name='school',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='Menu.book', verbose_name='Китобҳои мактаб'),
        ),
        migrations.AddField(
            model_name='school',
            name='students_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Китобҳое, ки аз ҷониби донишҷӯён гирифта шудаанд'),
        ),
    ]
