# Generated by Django 4.2.16 on 2025-04-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_remove_school_books_remove_school_students_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='Menu.grade'),
        ),
    ]
