# Generated by Django 4.2.16 on 2025-04-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_purchase_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade1', to='Menu.grade'),
        ),
    ]
