# Generated by Django 4.2.16 on 2025-04-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_payment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Menu.grade'),
        ),
    ]
