# Generated by Django 4.2.16 on 2025-04-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_alter_payment_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='grade',
        ),
    ]
