# Generated by Django 4.2.17 on 2025-04-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_customuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menu.school'),
        ),
    ]
